-- Supabase seed data for color identities, common Commander archetypes, and sample records.
-- Lookup rows are idempotent so local resets and repeated seeds stay predictable.

INSERT INTO color_identities (code, name, white, blue, black, red, green) VALUES
('C', 'Colorless', FALSE, FALSE, FALSE, FALSE, FALSE),
('W', 'Mono-White', TRUE, FALSE, FALSE, FALSE, FALSE),
('U', 'Mono-Blue', FALSE, TRUE, FALSE, FALSE, FALSE),
('B', 'Mono-Black', FALSE, FALSE, TRUE, FALSE, FALSE),
('R', 'Mono-Red', FALSE, FALSE, FALSE, TRUE, FALSE),
('G', 'Mono-Green', FALSE, FALSE, FALSE, FALSE, TRUE),
('WU', 'Azorius', TRUE, TRUE, FALSE, FALSE, FALSE),
('UB', 'Dimir', FALSE, TRUE, TRUE, FALSE, FALSE),
('BR', 'Rakdos', FALSE, FALSE, TRUE, TRUE, FALSE),
('RG', 'Gruul', FALSE, FALSE, FALSE, TRUE, TRUE),
('GW', 'Selesnya', TRUE, FALSE, FALSE, FALSE, TRUE),
('WB', 'Orzhov', TRUE, FALSE, TRUE, FALSE, FALSE),
('UR', 'Izzet', FALSE, TRUE, FALSE, TRUE, FALSE),
('BG', 'Golgari', FALSE, FALSE, TRUE, FALSE, TRUE),
('RW', 'Boros', TRUE, FALSE, FALSE, TRUE, FALSE),
('GU', 'Simic', FALSE, TRUE, FALSE, FALSE, TRUE),
('WUB', 'Esper', TRUE, TRUE, TRUE, FALSE, FALSE),
('UBR', 'Grixis', FALSE, TRUE, TRUE, TRUE, FALSE),
('BRG', 'Jund', FALSE, FALSE, TRUE, TRUE, TRUE),
('RGW', 'Naya', TRUE, FALSE, FALSE, TRUE, TRUE),
('GWU', 'Bant', TRUE, TRUE, FALSE, FALSE, TRUE),
('WBG', 'Abzan', TRUE, FALSE, TRUE, FALSE, TRUE),
('URW', 'Jeskai', TRUE, TRUE, FALSE, TRUE, FALSE),
('BGU', 'Sultai', FALSE, TRUE, TRUE, FALSE, TRUE),
('RWB', 'Mardu', TRUE, FALSE, TRUE, TRUE, FALSE),
('GUR', 'Temur', FALSE, TRUE, FALSE, TRUE, TRUE),
('WUBR', 'Yore-Tiller', TRUE, TRUE, TRUE, TRUE, FALSE),
('UBRG', 'Glint-Eye', FALSE, TRUE, TRUE, TRUE, TRUE),
('BRGW', 'Dune-Brood', TRUE, FALSE, TRUE, TRUE, TRUE),
('RGWU', 'Ink-Treader', TRUE, TRUE, FALSE, TRUE, TRUE),
('GWUB', 'Witch-Maw', TRUE, TRUE, TRUE, FALSE, TRUE),
('WUBRG', 'Five-Color', TRUE, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    white = EXCLUDED.white,
    blue = EXCLUDED.blue,
    black = EXCLUDED.black,
    red = EXCLUDED.red,
    green = EXCLUDED.green;

INSERT INTO archetypes (name, description) VALUES
('-1/-1 Counters', 'Controls the board by adding negative counters to opponents creatures.'),
('+1/+1 Counters', 'Buffs creatures by adding counters and wins through combat.'),
('Aggro', 'Wins through fast pressure and efficient combat damage.'),
('Aristocrats', 'Sacrifices creatures or permanents for incremental value and drain effects.'),
('Artifacts', 'Builds around artifact permanents, synergies, and payoffs.'),
('Blink', 'Exiles and returns permanents to reuse enter-the-battlefield effects.'),
('Burn', 'Deals damage directly to opponents in small increments over time'),
('Combo', 'Assembles specific card interactions that can win or generate overwhelming advantage.'),
('Control', 'Slows the game with removal, counters, and resource denial before winning later.'),
('Enchantress', 'Builds around enchantments and cards that reward casting or controlling them.'),
('Group Hug', 'Gives resources to other players while steering the table politically.'),
('Infect', 'Wins by giving each opponent 10 poison counters during the game'),
('Lands', 'Uses lands as the central engine for ramp, value, or win conditions.'),
('Lifegain', 'Uses life total increases as a resource or payoff engine.'),
('Mill', 'Attempts to put opponents cards from library into graveyard as a win condition.'),
('Reanimator', 'Moves creatures into the graveyard and returns them to the battlefield.'),
('Spellslinger', 'Rewards casting instants and sorceries.'),
('Stax', 'Restricts resources and actions to slow opponents down.'),
('Tokens', 'Creates many creature tokens and uses them for combat, sacrifice, or value.'),
('Tribal', 'Focuses on a creature type and cards that reward that type.'),
('Voltron', 'Builds around making one commander or creature large and threatening.'),
('Wheel', 'Forces players to discard and draw new hands for disruption or payoff triggers.'),
('X-spells', 'Ramps quickly to be able to cast bigger and bigger spells.')
ON CONFLICT (name) DO UPDATE SET
    description = EXCLUDED.description;
